# Generated by Django 5.0.6 on 2024-06-16 22:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, help_text='Comma-separated list of tags', null=True, size=5, verbose_name='Tags')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Summary')),
                ('status', models.CharField(blank=True, choices=[('Publish', 'Publish'), ('Reject', 'Reject'), ('Draft', 'Draft'), ('waiting for publish', 'Waiting')], default='Draft', max_length=40)),
                ('cover', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cover')),
                ('body', models.TextField(verbose_name='Body')),
                ('view_cnt', models.PositiveIntegerField(blank=True, default=0, verbose_name='View count')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('is_commentable', models.BooleanField(blank=True, default=True, verbose_name='Allow Send Comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('published', models.DateField(auto_now_add=True, verbose_name='Publish Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('categories', models.ManyToManyField(related_name='articles', to='article.category', verbose_name='Categories')),
            ],
        ),
    ]
