# Generated by Django 5.0.6 on 2024-06-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('Publish', 'Publish'), ('Reject', 'Reject'), ('Draft', 'Draft'), ('Waiting', 'Waiting')], default='Draft', max_length=40),
        ),
    ]
